name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: |
          .\PublishBCApp.ps1
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: whoami
        run: |
          whoami
      - name: List containers
        run: |
          docker ps
      - name: List ServerInstance
        run: |
          Invoke-ScriptInNavContainer -containername $containerName -scriptblock {Get-NavServerInstance BC}
      - name: run one test
        run: |
              $containerName = "MyLocalBC"
              $userName = "test"
              $userPswrd = "test"
              $xunitResultsFile = "C:\ProgramData\BcContainerHelper\Extensions\MyLocalBC\BCTechDays.xml"
              $securePassword = ConvertTo-SecureString -String $userPswrd -AsPlainText -Force
              $credential = New-Object System.Management.Automation.PSCredential -argumentList $userName, $securePassword
              Run-TestsInBCContainer `
              -containerName $containerName `
              -credential $credential `
              -testSuite 'DEFAULT' `
              -testFunction 'CreateNewUser' `
              -detailed `
              -XUnitResultFileName $xunitResultsFile `
              -returnTrueIfAllPassed 
      - run: echo "üçè This job's status is ${{ job.status }}."
